# Generated by Django 5.2.13 on 2026-09-21 07:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventree_mbom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partrouting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=4, help_text='Labor cost per hour in the configured currency', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='machinecenter',
            name='co2_factor_per_minute',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='CO₂ equivalent emissions per minute of machine operation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='CO₂ Factor (kg/min)'),
        ),
        migrations.AlterField(
            model_name='machinecenter',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=4, help_text='Machine operating cost per hour (power, depreciation, tooling)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='machinecenter',
            name='name',
            field=models.CharField(help_text='Machine center name (e.g. 5-Axis CNC, Reflow Oven)', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partrouting',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Template this routing was seeded from (informational)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_routings', to='inventree_mbom.processtemplate', verbose_name='Source Template'),
        ),
        migrations.AlterField(
            model_name='partrouting',
            name='standard_batch_size',
            field=models.PositiveIntegerField(default=1, help_text='Used to amortise setup costs into per-unit cost', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Standard Batch Size'),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='parent_step',
            field=models.ForeignKey(blank=True, help_text='Leave blank for top-level operations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_steps', to='inventree_mbom.processtemplatestep', verbose_name='Parent Step'),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='run_time_per_unit_minutes',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cycle time per unit in minutes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Run Time per Unit (min)'),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='setup_time_minutes',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Fixed setup time in minutes (charged once per batch)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Setup Time (min)'),
        ),
    ]
